spring.application.name=Proyecto
server.port=91

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

#Esta información se utiliza para obtener acceso a su storage.
firebase.bucket.name=xxxxx.firebasestorage.app
firebase.storage.path=xxxxx
firebase.json.path=firebase
firebase.json.file=xxxx.json